config/routes.rb
Rails.application.routes.draw do

   resources :passwords, controller: "clearance/passwords", only: [:create, :new]
   resource :session, controller: "clearance/sessions", only: [:create]

    resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
             controller: "clearance/passwords",
             only: [:create, :edit, :update]
    end

  resources :pages, only: [:new]

  constraints Clearance::Constraints::SignedIn.new do
    root to: 'pages#new', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'pages#index'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :require_login, only: [:new]
  def index
  end

  def new
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>ClearSky</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Clear Sky', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <% if signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Add Page', new_page_path %></li>
        </ul>
      <% end %>

      <ul class="nav navbar-nav pull-right">
        <% if signed_in? %>
          <li><span><%= current_user.email %></span></li>
          <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', sign_in_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>

  <div id="footer">
    <div class="container-fluid">
      <p class="text-muted">Created by <a href="http://radiant-wind.com" target="_blank">Radiant Wind</a></p>
    </div>
  </div>
</div>

</body>
</html>

app/views/pages/index.html.erb
<div class="page-header"><h1>Welcome!</h1></div>

app/views/pages/new.html.erb
<div class="page-header"><h1>Add Page</h1></div>